package models

type Attachment struct {
	ContentType string  `json:"contentType"`
	Content     Content `json:"content"`
}

type AutoGenerated struct {
	ContentType string  `json:"contentType"`
	Content     Content `json:"content"`
}
type Body struct {
	Type string `json:"type"`
	Text string `json:"text"`
	Size string `json:"size"`
}
type Actions struct {
	Type  string `json:"type"`
	URL   string `json:"url"`
	Title string `json:"title"`
}
type Content struct {
	Type    string    `json:"type"`
	Version string    `json:"version"`
	Body    []Body    `json:"body"`
	Actions []Actions `json:"actions"`
}
